spring.application.name=Spring_Boot_Rest_API-React

server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5433/spring_boot_API_React
spring.datasource.username=postgres
spring.datasource.password=4518

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

